### ISSUE TITLE
Error while cleaning up logs files

### ISSUE THREAD

**Issue by HanzelM** [Mirdarthos/manjaro-update-helper#14]
When using `mumuh -s` this pops up at the end. 

Cleaning older log files...
/usr/bin/mumuh: line 562: cd: /var/log/manjaro-update-helper: No such file or directory

**Comment by Mirdarthos** [comment]
Thank you. Will have  a look.

**Comment by Mirdarthos** [comment]
Updated `mumuh`. Please check now.

**Comment by HanzelM** [comment]
Error is gone, thanks :)
