### ISSUE TITLE
Mirror status 

### ISSUE THREAD

**Issue by HanzelM** [Mirdarthos/manjaro-update-helper#4]
When updating the status of the selected mirrors is a worthwhile data point to have for troubleshooting. 

`pacman-mirrors --status` reports the mirrors and status in this format: 
```
Local mirror status for unstable branch
Mirror #1   --  06:57   Netherlands  http://ftp.snt.utwente.nl/pub/linux/manjaro/
Mirror #2   --  05:21   Netherlands  https://mirror.koddos.net/manjaro/
Mirror #3   OK  00:21   Netherlands  https://manjaro.mirrors.lavatech.top/
Mirror #4   OK  01:06   Global       https://mirrors.fossho.st/manjaro/

```
In this example only mirrors 3 & 4  are up to date but this should not be an issue with the update since pamac should use only up-to-date mirrors.  The goal should be to report a failure if there are no up-to-date mirrors, informing the user about the status of the selected mirrors.

**Comment by Mirdarthos** [comment]
Implemented debug info in generated forum post.
