### ISSUE TITLE
Add cache deletion after upgrade

### ISSUE THREAD

**Issue by Mirdarthos** [Mirdarthos/manjaro-update-helper#6]
Add option to delete users' caches after an upgrade.

**Comment by Mirdarthos** [comment]
**Needs more research.**

**Comment by Mirdarthos** [comment]
@yochananmarqos, do you, perhaps, know of a safe way to clear the users' `~/.cache` directory?
I was tinking of doing it manually, looping thorough the home directories and removing the contents of the `~/.cache` directory if it's present. But I don't really want to do it as `root` since that would mean changing the home directory contents with `root` and  I don't  want to. Nevermind that it goes against the rest of the system's not touching your home directory.

Otherwise, it'll have to be only for the _current_ user, which is, in my opinion, not optimal.

**Comment by yochananmarqos** [comment]
> Nevermind that it goes against the rest of the system's not touching your home directory.

I think you just answered your own question.

Also, advise for clearing the cache on any OS is usually snake oil to sell products.

**Comment by Mirdarthos** [comment]
Fair enough.

I Can't actually with any honest6y say that I've had to clear my cache. Or at least not as a rule.
